version: "3.8"

services:

  # MariaDB is available at port 3306 inside the Compose network. For
  # development purposes, the root password is set to `root`.
  mariadb:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always

  # The app service waits for MariaDB and exposes its API on port 8000.
  # This example uses environment variables for configuring MariaDB access,
  # but CLI flags would work fine, too.
  todo:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 8000:8000
    environment:
      TODO_MARIADB_USER: root
      TODO_MARIADB_PASSWORD: root
      TODO_MARIADB_ADDRESS: mariadb:3306
      WAIT_HOSTS: mariadb:3306