swagger: '2.0'
info:
  version: 1.0.0
  title: ToDo App
  contact:
    email: mail@dominikbraun.io
paths:
  /todos:
    post:
      summary: Creates a new ToDo
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/ToDo'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/ToDo'
        '422':
          description: Invalid ToDo structure
    get:
      summary: Returns a list of all ToDos
      responses:
        '200':
          description: Success
          schema:
            type: array
            items:
              $ref: '#/definitions/ToDo'
  '/todos/{id}':
    get:
      summary: Returns a ToDo
      parameters:
        - name: id
          in: path
          description: ID of the ToDo
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/ToDo'
        '404':
          description: ToDo not found
    put:
      summary: Overwrites an existing Todo
      parameters:
        - name: id
          in: path
          description: ID of the ToDo
          required: true
          type: integer
          format: int64
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/ToDo'
      responses:
        '200':
          description: Success
        '404':
          description: ToDo not found
        '422':
          description: Invalid ToDo structure
    delete:
      summary: Deletes a ToDo
      parameters:
        - name: id
          in: path
          description: ID of the ToDo
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: Success
        '404':
          description: ToDo not found
definitions:
  ToDo:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
        example: My ToDo
      description:
        type: string
        example: My ToDo Description
      tasks:
        type: array
        items:
          $ref: '#/definitions/Task'
  Task:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
        example: A Task
      description:
        type: string
        example: A Task Description